### ISSUE TITLE
Fraud and Scams - There needs to be a distinction between long and short cons

### ISSUE THREAD

**Issue by ISNIT0** [delight-im/Knowledge#3]
Short and long cons are distinct.

They should probably be distinguished between.
See Hustle (BBC UK)

**Comment by mwaclawek** [comment]
Thank you very much!

The confidence tricks should have been classified as either short cons or long cons in https://github.com/delight-im/Knowledge/commit/bfb6d8d1e23d32eac58c20030168d60ccce3ce3c so that they are in (hopefully correct) distinct groups now: https://github.com/delight-im/Knowledge/blob/bfb6d8d1e23d32eac58c20030168d60ccce3ce3c/Fraud%20and%20Scams.md

**Comment by ISNIT0** [comment]
+1
